### ISSUE TITLE
An Option to Output for Streaming

### ISSUE THREAD

**Issue by devdazed** [tolbertam/sstable-tools#19]
Reading the entire SSTable into memory when analyzing the output of sstable2json is rather cumbersome and sometimes not feasible/possible given the size of the resulting JSON.  

Having a command line option that would output one partition object per line (or by some other delimiter), would solve this by allowing a user to load one partition at a time into memory. While partition sizes can get rather large, they will not be as large as the SSTable itself.

This output would then have no need to output the beginning and ending array brackets, nor the trailing comma after each of the partitions.  

I can also see a possible performance benefit here as you can read the SSTable and output each partition as you read it, rather than reading the entire SSTable in all at once.

**Comment by clohfink** [comment]
partition per line would still be issue, but I think a row per line would make this pretty doable so I am all for doing that here and will put it on list right after json2sstable that I'm working on currently.

That said there are streaming json libraries available, jackson, jsonsimple in javaland, and I've used ijson in python to read huge sstables with old sstable2json succesfully.

**Comment by devdazed** [comment]
I've heard about the streaming libraries, however they tend to be rather cumbersome to use, at least the python ones I've tried were.  One row per line seems a bit of an issue also as the format you have outlined would not really help because the partition start and end would be on different lines, unless you want to output in a completely different format that duplicates the partition information on every row?. 

The idea is to be able to parse with something simple like:

``` python
import sys, json
tombstones = 0

for line in sys.stdin:
    partition = json.loads(line)
    for row in partition['rows']:
        if 'deletion_info' in row:
            tombstones += 1
            continue
        for cell in row.get('cells'):
            if 'deletion_time' in cell:
                tombstones += 1

print str(tombstones) + " tombstones found"
```

the example above is a bit contrived and might even not work, but it demonstrates a valid and common use case for parsing SSTables, is to find tombstone where there may be clusters of tombstones that can cause issues in the cluster.

**Comment by devdazed** [comment]
also streaming json libraries tend to be rather slow as they sometimes rely on continually attempting to parse incomplete json and catching the exceptions

**Comment by clohfink** [comment]
I tend to worry about doing a partition per line when the concern is OOMing when reading at once. a >1gb partition is bad but far from unheard of - id say its seen a lot in time-seriesey applications. Adding the json overhead this would demolish systems as well. That said I dont know of a good solution short of a weird state machine/custom parsing so maybe a partition per line is best and people with wide rows have to use incremental parsers.

FWIW if you use this as a library instead of a tool its pretty easy. might be good idea for us to add to mvn or something if valuable

``` java
final AtomicInteger total = new AtomicInteger(0);
CassandraReader.fromSSTable(sstablePath).readSSTable(sstablePath, null)
        .filter(p -> p.isLive())
        .forEach(p -> {
            p.rows().forEach(unfiltered -> {
                if (unfiltered instanceof Row) {
                    for (Cell cell : ((Row) unfiltered).cells()){
                        if(!cell.isLive((int)(System.currentTimeMillis() / 1000))) {
                            total.incrementAndGet();
                        }...
```

**Comment by devdazed** [comment]
could always do a cell per line and include all partition key info and deletion info in the object.  this will keep objects small and, since everything is sorted, the apps will know when the next partition/row happens because it will change. it will, however, drastically increase the file size if outputting to a file.

also, what about complex types and things like sets, lists.  if a row has a 1gb set, this could also be problematic.

generally people doing exceptional things with their partitions are going to be the ones who need this tool the most.  it makes most sense to optimize it for those who will need it, rather than for the majority of Cassandra users who will almost never need to use the tool.

**Comment by clohfink** [comment]
#23

**Comment by tolbertam** [comment]
Closing since this now exists as the `-d` option in sstabledump (which is no longer part of sstable-tools but part of sstabledump in C*)
