### ISSUE TITLE
It doesn't work with C* 2.1.5

### ISSUE THREAD

**Issue by Krasnyanskiy** [tolbertam/sstable-tools#20]
In [this](https://github.com/tolbertam/sstable-tools/blob/master/src/main/java/com/csforge/sstable/reader/CassandraReader.java#L71) line method `get` returns a `null` which leads to `NPE`.

**Comment by clohfink** [comment]
2.1 and 2.2 have a sstable2json tool built in. In 3.0 with storage engine changes things changed so much they just dropped the tool.  This tool targets 3.x+. Previous versions won't work unfortunately as the api to access the data changed so drastically. I would recommend using your bin/sstable2json for now.

**Comment by Krasnyanskiy** [comment]
Oh, I see. Thanks.
