### ISSUE TITLE
support C* 2.1 version

### ISSUE THREAD

**Issue by wavelet123** [tolbertam/sstable-tools#71]
Hi,
Can this support C* 2.1 version?
as many users are still using C* 2.x version.
Thanks

**Comment by tolbertam** [comment]
Hi @wavelet123,

Unfortunately, there isn't an easy way to do that.  The initial motivation for sstable-tools was to provide tooling that was missing in C* 3.0 but was present in C* 2.x, that being the `sstable2json` command.  

We implemented an `sstable2json` for C* 3.0 in sstable-tools that was eventually merged into C* and named `sstabledump` ([article](https://www.datastax.com/dev/blog/debugging-sstables-in-3-0-with-sstabledump)).

The remaining useful tooling in sstable-tools (cli, describe, etc.) is mostly experimental and was written solely for C* 3.x.
