### ISSUE TITLE
Use java driver to pull meta data

### ISSUE THREAD

**Issue by clohfink** [tolbertam/sstable-tools#8]
If the -c option is not provided attempt to connect to cluster (use defaults unless overriden) and retrieve the tables schema. Not necessary if #7 is successful.

**Comment by clohfink** [comment]
with the pulling types from the statistics tables, is this still necessary? I think we can close this

**Comment by tolbertam** [comment]
I agree, I don't think we really need it now with your implementation in #15, closing :+1:
